name: flutter_painter
version: 0.2.1
description: A Flutter widget to draw scribbles, text and shapes on a background image or color
homepage: https://github.com/omarhurani/flutter_painter
repository: https://github.com/omarhurani/flutter_painter
issue_tracker: https://github.com/omarhurani/flutter_painter/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: